### ISSUE TITLE
Insert row on child table

### ISSUE THREAD

**Issue by abue90** [frappe/frappe-client#14]
As per title, how  to do so?
I have try by inserting new document to the Child Doctype. However, i got this error in return:
![image](https://cloud.githubusercontent.com/assets/15136489/19852644/74a34710-9f9f-11e6-8932-99d8d0144b6b.png)

Any help is much appreciated

**Comment by nabinhait** [comment]
@abue90 Can you please post this in discuss.erpnext.com? Also, please share your code there.
