### ISSUE TITLE
Frappe-Client.INSERT : : No JSON Object could be decoded

### ISSUE THREAD

**Issue by nirajKpanda** [frappe/frappe-client#23]
Code : 

import json
from frappeclient import FrappeClient

data = json.loads(open("user.json").read())

client = FrappeClient("http://localhost:5000", "xxxxxxx", "xxxxxxxx")
notes = [
        {
         "doctype": "Employee",
         "eid" : "242",
         "name" : "niraj1",
         "dob" : "05-05-1993",
         "doj" : "01-08-1993",
         "dept" : "R&D",
         "manager" : "raghu"
}]

print(client.insert(notes[0]))

Error:
Traceback (most recent call last):
  File "client.py", line 32, in <module>
    print(client.insert(notes[0]))
  File "/home/niraj/workspace/frappe-client/frappeclient/frappeclient.py", line 53, in insert
    return self.post_process(res)
  File "/home/niraj/workspace/frappe-client/frappeclient/frappeclient.py", line 203, in post_process
    rjson = response.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Can anyone help me here I am really banging my head in this seems to be a silly issue?

-Niraj

**Comment by dawoodjee** [comment]
Hey @nirajKpanda 

Did you figure this one out?

**Comment by dawoodjee** [comment]
This is my code. Not sure whats wrong here

```
from frappeclient import FrappeClient
import pyodbc 

def set_uom():

    https = FrappeClient("https://me.com", "api", "Me1234")

    doc = https.insert({
            'doctype': 'Item Group',
            'parent': 'Foods',
            'name': 'new-group'
        })

set_uom()
```

**Comment by nirajKpanda** [comment]
It's working now.
Sorry for the long pending issue, should have closed it.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by dawoodjee** [comment]
> It's working now. Sorry for the long pending issue, should have closed it. Sent from Outlook Mobile<https://aka.ms/blhgte>


I'm also trying to solve this problem. What was your solution?

**Comment by nirajKpanda** [comment]
I stopped working on this project about 2 years back.
I don't have a code trace for reference. Sorry I could not be of help in this.

Hope wider Frappe community will help you in this.

Thanks,
Niraj Kumar Panda

________________________________

**Comment by dawoodjee** [comment]
The issue was a wrong field name. Item group name variable is `item_group_name` not `name`.

This resolved my issue.

Thanks for your time Niraj. I advise we close the issue now.
