### ISSUE TITLE
This still maintained?

### ISSUE THREAD

**Issue by mattronix** [frappe/frappe-client#28]
Is this still usable and suitable in prod? 

Is this still maintained?

**Comment by ddavidebor** [comment]
If this repo is obsolete please use the "Archive" github feature

**Comment by rmehta** [comment]
Released 1.0

**Comment by mingfang** [comment]
same question. this project appears to be abandoned.
There has been code changes to make Python 3 compatible which is good, but no new releases so have to install using git.
Also both examples don't work.
Please either commit to work on this or label as achieved to avoid wasting people's time.

**Comment by MrMauro** [comment]
I second this:
> Please either commit to work on this or label as achieved to avoid wasting people's time.
